// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: agent_property_grants.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAgentPropertyGrant = `-- name: CreateAgentPropertyGrant :one
INSERT INTO agent_property_grants (
    agent_id, property_id, can_record_payments, can_edit_leases,
    can_edit_unit_pricing, can_void_payments, can_view_financial_reports,
    can_manage_meter_readings, granted_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, agent_id, property_id, can_record_payments, can_edit_leases, can_edit_unit_pricing, can_void_payments, can_view_financial_reports, can_manage_meter_readings, granted_by, granted_at, revoked_at
`

type CreateAgentPropertyGrantParams struct {
	AgentID                 pgtype.UUID
	PropertyID              pgtype.UUID
	CanRecordPayments       bool
	CanEditLeases           bool
	CanEditUnitPricing      bool
	CanVoidPayments         bool
	CanViewFinancialReports bool
	CanManageMeterReadings  bool
	GrantedBy               pgtype.UUID
}

func (q *Queries) CreateAgentPropertyGrant(ctx context.Context, arg CreateAgentPropertyGrantParams) (AgentPropertyGrant, error) {
	row := q.db.QueryRow(ctx, createAgentPropertyGrant,
		arg.AgentID,
		arg.PropertyID,
		arg.CanRecordPayments,
		arg.CanEditLeases,
		arg.CanEditUnitPricing,
		arg.CanVoidPayments,
		arg.CanViewFinancialReports,
		arg.CanManageMeterReadings,
		arg.GrantedBy,
	)
	var i AgentPropertyGrant
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.PropertyID,
		&i.CanRecordPayments,
		&i.CanEditLeases,
		&i.CanEditUnitPricing,
		&i.CanVoidPayments,
		&i.CanViewFinancialReports,
		&i.CanManageMeterReadings,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.RevokedAt,
	)
	return i, err
}

const deleteAgentPropertyGrant = `-- name: DeleteAgentPropertyGrant :exec
DELETE FROM agent_property_grants WHERE id = $1
`

func (q *Queries) DeleteAgentPropertyGrant(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteAgentPropertyGrant, id)
	return err
}

const getAgentPropertyGrant = `-- name: GetAgentPropertyGrant :one
SELECT id, agent_id, property_id, can_record_payments, can_edit_leases, can_edit_unit_pricing, can_void_payments, can_view_financial_reports, can_manage_meter_readings, granted_by, granted_at, revoked_at FROM agent_property_grants WHERE id = $1
`

func (q *Queries) GetAgentPropertyGrant(ctx context.Context, id pgtype.UUID) (AgentPropertyGrant, error) {
	row := q.db.QueryRow(ctx, getAgentPropertyGrant, id)
	var i AgentPropertyGrant
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.PropertyID,
		&i.CanRecordPayments,
		&i.CanEditLeases,
		&i.CanEditUnitPricing,
		&i.CanVoidPayments,
		&i.CanViewFinancialReports,
		&i.CanManageMeterReadings,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.RevokedAt,
	)
	return i, err
}

const listAgentPropertyGrantsByAgent = `-- name: ListAgentPropertyGrantsByAgent :many
SELECT id, agent_id, property_id, can_record_payments, can_edit_leases, can_edit_unit_pricing, can_void_payments, can_view_financial_reports, can_manage_meter_readings, granted_by, granted_at, revoked_at FROM agent_property_grants WHERE agent_id = $1
`

func (q *Queries) ListAgentPropertyGrantsByAgent(ctx context.Context, agentID pgtype.UUID) ([]AgentPropertyGrant, error) {
	rows, err := q.db.Query(ctx, listAgentPropertyGrantsByAgent, agentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentPropertyGrant{}
	for rows.Next() {
		var i AgentPropertyGrant
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.PropertyID,
			&i.CanRecordPayments,
			&i.CanEditLeases,
			&i.CanEditUnitPricing,
			&i.CanVoidPayments,
			&i.CanViewFinancialReports,
			&i.CanManageMeterReadings,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAgentPropertyGrantsByProperty = `-- name: ListAgentPropertyGrantsByProperty :many
SELECT id, agent_id, property_id, can_record_payments, can_edit_leases, can_edit_unit_pricing, can_void_payments, can_view_financial_reports, can_manage_meter_readings, granted_by, granted_at, revoked_at FROM agent_property_grants WHERE property_id = $1
`

func (q *Queries) ListAgentPropertyGrantsByProperty(ctx context.Context, propertyID pgtype.UUID) ([]AgentPropertyGrant, error) {
	rows, err := q.db.Query(ctx, listAgentPropertyGrantsByProperty, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AgentPropertyGrant{}
	for rows.Next() {
		var i AgentPropertyGrant
		if err := rows.Scan(
			&i.ID,
			&i.AgentID,
			&i.PropertyID,
			&i.CanRecordPayments,
			&i.CanEditLeases,
			&i.CanEditUnitPricing,
			&i.CanVoidPayments,
			&i.CanViewFinancialReports,
			&i.CanManageMeterReadings,
			&i.GrantedBy,
			&i.GrantedAt,
			&i.RevokedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateAgentPropertyGrant = `-- name: UpdateAgentPropertyGrant :one
UPDATE agent_property_grants SET
    can_record_payments = $2,
    can_edit_leases = $3,
    can_edit_unit_pricing = $4,
    can_void_payments = $5,
    can_view_financial_reports = $6,
    can_manage_meter_readings = $7,
    revoked_at = $8
WHERE id = $1
RETURNING id, agent_id, property_id, can_record_payments, can_edit_leases, can_edit_unit_pricing, can_void_payments, can_view_financial_reports, can_manage_meter_readings, granted_by, granted_at, revoked_at
`

type UpdateAgentPropertyGrantParams struct {
	ID                      pgtype.UUID
	CanRecordPayments       bool
	CanEditLeases           bool
	CanEditUnitPricing      bool
	CanVoidPayments         bool
	CanViewFinancialReports bool
	CanManageMeterReadings  bool
	RevokedAt               pgtype.Timestamptz
}

func (q *Queries) UpdateAgentPropertyGrant(ctx context.Context, arg UpdateAgentPropertyGrantParams) (AgentPropertyGrant, error) {
	row := q.db.QueryRow(ctx, updateAgentPropertyGrant,
		arg.ID,
		arg.CanRecordPayments,
		arg.CanEditLeases,
		arg.CanEditUnitPricing,
		arg.CanVoidPayments,
		arg.CanViewFinancialReports,
		arg.CanManageMeterReadings,
		arg.RevokedAt,
	)
	var i AgentPropertyGrant
	err := row.Scan(
		&i.ID,
		&i.AgentID,
		&i.PropertyID,
		&i.CanRecordPayments,
		&i.CanEditLeases,
		&i.CanEditUnitPricing,
		&i.CanVoidPayments,
		&i.CanViewFinancialReports,
		&i.CanManageMeterReadings,
		&i.GrantedBy,
		&i.GrantedAt,
		&i.RevokedAt,
	)
	return i, err
}
