// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_log.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAuditLogEntry = `-- name: CreateAuditLogEntry :one
INSERT INTO audit_log (
    organization_id, property_id, actor_id, action, entity_type, entity_id, metadata
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, property_id, actor_id, action, entity_type, entity_id, metadata, created_at
`

type CreateAuditLogEntryParams struct {
	OrganizationID pgtype.UUID
	PropertyID     pgtype.UUID
	ActorID        pgtype.UUID
	Action         string
	EntityType     string
	EntityID       pgtype.UUID
	Metadata       []byte
}

func (q *Queries) CreateAuditLogEntry(ctx context.Context, arg CreateAuditLogEntryParams) (AuditLog, error) {
	row := q.db.QueryRow(ctx, createAuditLogEntry,
		arg.OrganizationID,
		arg.PropertyID,
		arg.ActorID,
		arg.Action,
		arg.EntityType,
		arg.EntityID,
		arg.Metadata,
	)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PropertyID,
		&i.ActorID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const getAuditLogEntry = `-- name: GetAuditLogEntry :one
SELECT id, organization_id, property_id, actor_id, action, entity_type, entity_id, metadata, created_at FROM audit_log WHERE id = $1
`

func (q *Queries) GetAuditLogEntry(ctx context.Context, id pgtype.UUID) (AuditLog, error) {
	row := q.db.QueryRow(ctx, getAuditLogEntry, id)
	var i AuditLog
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.PropertyID,
		&i.ActorID,
		&i.Action,
		&i.EntityType,
		&i.EntityID,
		&i.Metadata,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditLog = `-- name: ListAuditLog :many
SELECT id, organization_id, property_id, actor_id, action, entity_type, entity_id, metadata, created_at FROM audit_log ORDER BY created_at DESC
`

func (q *Queries) ListAuditLog(ctx context.Context) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLog)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PropertyID,
			&i.ActorID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditLogByProperty = `-- name: ListAuditLogByProperty :many
SELECT id, organization_id, property_id, actor_id, action, entity_type, entity_id, metadata, created_at FROM audit_log WHERE property_id = $1 ORDER BY created_at DESC
`

func (q *Queries) ListAuditLogByProperty(ctx context.Context, propertyID pgtype.UUID) ([]AuditLog, error) {
	rows, err := q.db.Query(ctx, listAuditLogByProperty, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditLog{}
	for rows.Next() {
		var i AuditLog
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.PropertyID,
			&i.ActorID,
			&i.Action,
			&i.EntityType,
			&i.EntityID,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
