// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: invoices.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createInvoice = `-- name: CreateInvoice :one
INSERT INTO invoices (
    organization_id, lease_id, period_month, invoice_type,
    amount_due, status, meter_reading_id
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING id, organization_id, lease_id, period_month, invoice_type, amount_due, amount_paid, balance, status, meter_reading_id, created_at
`

type CreateInvoiceParams struct {
	OrganizationID pgtype.UUID
	LeaseID        pgtype.UUID
	PeriodMonth    pgtype.Date
	InvoiceType    InvoiceKind
	AmountDue      pgtype.Numeric
	Status         InvoiceStatus
	MeterReadingID pgtype.UUID
}

func (q *Queries) CreateInvoice(ctx context.Context, arg CreateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, createInvoice,
		arg.OrganizationID,
		arg.LeaseID,
		arg.PeriodMonth,
		arg.InvoiceType,
		arg.AmountDue,
		arg.Status,
		arg.MeterReadingID,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.LeaseID,
		&i.PeriodMonth,
		&i.InvoiceType,
		&i.AmountDue,
		&i.AmountPaid,
		&i.Balance,
		&i.Status,
		&i.MeterReadingID,
		&i.CreatedAt,
	)
	return i, err
}

const deleteInvoice = `-- name: DeleteInvoice :exec
DELETE FROM invoices WHERE id = $1
`

func (q *Queries) DeleteInvoice(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteInvoice, id)
	return err
}

const getInvoice = `-- name: GetInvoice :one
SELECT id, organization_id, lease_id, period_month, invoice_type, amount_due, amount_paid, balance, status, meter_reading_id, created_at FROM invoices WHERE id = $1
`

func (q *Queries) GetInvoice(ctx context.Context, id pgtype.UUID) (Invoice, error) {
	row := q.db.QueryRow(ctx, getInvoice, id)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.LeaseID,
		&i.PeriodMonth,
		&i.InvoiceType,
		&i.AmountDue,
		&i.AmountPaid,
		&i.Balance,
		&i.Status,
		&i.MeterReadingID,
		&i.CreatedAt,
	)
	return i, err
}

const listInvoicesByLease = `-- name: ListInvoicesByLease :many
SELECT id, organization_id, lease_id, period_month, invoice_type, amount_due, amount_paid, balance, status, meter_reading_id, created_at FROM invoices WHERE lease_id = $1 ORDER BY period_month
`

func (q *Queries) ListInvoicesByLease(ctx context.Context, leaseID pgtype.UUID) ([]Invoice, error) {
	rows, err := q.db.Query(ctx, listInvoicesByLease, leaseID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Invoice{}
	for rows.Next() {
		var i Invoice
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.LeaseID,
			&i.PeriodMonth,
			&i.InvoiceType,
			&i.AmountDue,
			&i.AmountPaid,
			&i.Balance,
			&i.Status,
			&i.MeterReadingID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateInvoice = `-- name: UpdateInvoice :one
UPDATE invoices SET
    amount_due = $2,
    status = $3,
    meter_reading_id = $4
WHERE id = $1
RETURNING id, organization_id, lease_id, period_month, invoice_type, amount_due, amount_paid, balance, status, meter_reading_id, created_at
`

type UpdateInvoiceParams struct {
	ID             pgtype.UUID
	AmountDue      pgtype.Numeric
	Status         InvoiceStatus
	MeterReadingID pgtype.UUID
}

func (q *Queries) UpdateInvoice(ctx context.Context, arg UpdateInvoiceParams) (Invoice, error) {
	row := q.db.QueryRow(ctx, updateInvoice,
		arg.ID,
		arg.AmountDue,
		arg.Status,
		arg.MeterReadingID,
	)
	var i Invoice
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.LeaseID,
		&i.PeriodMonth,
		&i.InvoiceType,
		&i.AmountDue,
		&i.AmountPaid,
		&i.Balance,
		&i.Status,
		&i.MeterReadingID,
		&i.CreatedAt,
	)
	return i, err
}
