// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: leases.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLease = `-- name: CreateLease :one
INSERT INTO leases (
    unit_id, tenant_id, monthly_rent, deposit_paid, start_date, end_date,
    rent_due_day, late_fee_pct_per_day, status, terminated_reason, created_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING id, unit_id, tenant_id, monthly_rent, deposit_paid, start_date, end_date, rent_due_day, late_fee_pct_per_day, status, terminated_reason, terminated_at, created_by, created_at
`

type CreateLeaseParams struct {
	UnitID           pgtype.UUID
	TenantID         pgtype.UUID
	MonthlyRent      pgtype.Numeric
	DepositPaid      pgtype.Numeric
	StartDate        pgtype.Date
	EndDate          pgtype.Date
	RentDueDay       int16
	LateFeePctPerDay pgtype.Numeric
	Status           LeaseStatus
	TerminatedReason pgtype.Text
	CreatedBy        pgtype.UUID
}

func (q *Queries) CreateLease(ctx context.Context, arg CreateLeaseParams) (Lease, error) {
	row := q.db.QueryRow(ctx, createLease,
		arg.UnitID,
		arg.TenantID,
		arg.MonthlyRent,
		arg.DepositPaid,
		arg.StartDate,
		arg.EndDate,
		arg.RentDueDay,
		arg.LateFeePctPerDay,
		arg.Status,
		arg.TerminatedReason,
		arg.CreatedBy,
	)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.TenantID,
		&i.MonthlyRent,
		&i.DepositPaid,
		&i.StartDate,
		&i.EndDate,
		&i.RentDueDay,
		&i.LateFeePctPerDay,
		&i.Status,
		&i.TerminatedReason,
		&i.TerminatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLease = `-- name: DeleteLease :exec
DELETE FROM leases WHERE id = $1
`

func (q *Queries) DeleteLease(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLease, id)
	return err
}

const getLease = `-- name: GetLease :one
SELECT id, unit_id, tenant_id, monthly_rent, deposit_paid, start_date, end_date, rent_due_day, late_fee_pct_per_day, status, terminated_reason, terminated_at, created_by, created_at FROM leases WHERE id = $1
`

func (q *Queries) GetLease(ctx context.Context, id pgtype.UUID) (Lease, error) {
	row := q.db.QueryRow(ctx, getLease, id)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.TenantID,
		&i.MonthlyRent,
		&i.DepositPaid,
		&i.StartDate,
		&i.EndDate,
		&i.RentDueDay,
		&i.LateFeePctPerDay,
		&i.Status,
		&i.TerminatedReason,
		&i.TerminatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listLeasesByUnit = `-- name: ListLeasesByUnit :many
SELECT id, unit_id, tenant_id, monthly_rent, deposit_paid, start_date, end_date, rent_due_day, late_fee_pct_per_day, status, terminated_reason, terminated_at, created_by, created_at FROM leases WHERE unit_id = $1 ORDER BY start_date
`

func (q *Queries) ListLeasesByUnit(ctx context.Context, unitID pgtype.UUID) ([]Lease, error) {
	rows, err := q.db.Query(ctx, listLeasesByUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Lease{}
	for rows.Next() {
		var i Lease
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.TenantID,
			&i.MonthlyRent,
			&i.DepositPaid,
			&i.StartDate,
			&i.EndDate,
			&i.RentDueDay,
			&i.LateFeePctPerDay,
			&i.Status,
			&i.TerminatedReason,
			&i.TerminatedAt,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLease = `-- name: UpdateLease :one
UPDATE leases SET
    monthly_rent = $2,
    deposit_paid = $3,
    start_date = $4,
    end_date = $5,
    rent_due_day = $6,
    late_fee_pct_per_day = $7,
    status = $8,
    terminated_reason = $9,
    terminated_at = $10
WHERE id = $1
RETURNING id, unit_id, tenant_id, monthly_rent, deposit_paid, start_date, end_date, rent_due_day, late_fee_pct_per_day, status, terminated_reason, terminated_at, created_by, created_at
`

type UpdateLeaseParams struct {
	ID               pgtype.UUID
	MonthlyRent      pgtype.Numeric
	DepositPaid      pgtype.Numeric
	StartDate        pgtype.Date
	EndDate          pgtype.Date
	RentDueDay       int16
	LateFeePctPerDay pgtype.Numeric
	Status           LeaseStatus
	TerminatedReason pgtype.Text
	TerminatedAt     pgtype.Timestamptz
}

func (q *Queries) UpdateLease(ctx context.Context, arg UpdateLeaseParams) (Lease, error) {
	row := q.db.QueryRow(ctx, updateLease,
		arg.ID,
		arg.MonthlyRent,
		arg.DepositPaid,
		arg.StartDate,
		arg.EndDate,
		arg.RentDueDay,
		arg.LateFeePctPerDay,
		arg.Status,
		arg.TerminatedReason,
		arg.TerminatedAt,
	)
	var i Lease
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.TenantID,
		&i.MonthlyRent,
		&i.DepositPaid,
		&i.StartDate,
		&i.EndDate,
		&i.RentDueDay,
		&i.LateFeePctPerDay,
		&i.Status,
		&i.TerminatedReason,
		&i.TerminatedAt,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}
