// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger_entries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerEntry = `-- name: CreateLedgerEntry :one
INSERT INTO ledger_entries (account_id, amount, transfer_id)
VALUES ($1, $2, $3)
RETURNING id, account_id, amount, transfer_id, created_at
`

type CreateLedgerEntryParams struct {
	AccountID  pgtype.UUID
	Amount     pgtype.Numeric
	TransferID pgtype.UUID
}

func (q *Queries) CreateLedgerEntry(ctx context.Context, arg CreateLedgerEntryParams) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, createLedgerEntry, arg.AccountID, arg.Amount, arg.TransferID)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.TransferID,
		&i.CreatedAt,
	)
	return i, err
}

const getLedgerEntry = `-- name: GetLedgerEntry :one
SELECT id, account_id, amount, transfer_id, created_at FROM ledger_entries WHERE id = $1
`

func (q *Queries) GetLedgerEntry(ctx context.Context, id pgtype.UUID) (LedgerEntry, error) {
	row := q.db.QueryRow(ctx, getLedgerEntry, id)
	var i LedgerEntry
	err := row.Scan(
		&i.ID,
		&i.AccountID,
		&i.Amount,
		&i.TransferID,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerEntriesByAccount = `-- name: ListLedgerEntriesByAccount :many
SELECT id, account_id, amount, transfer_id, created_at FROM ledger_entries WHERE account_id = $1 ORDER BY created_at
`

func (q *Queries) ListLedgerEntriesByAccount(ctx context.Context, accountID pgtype.UUID) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByAccount, accountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.TransferID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listLedgerEntriesByTransfer = `-- name: ListLedgerEntriesByTransfer :many
SELECT id, account_id, amount, transfer_id, created_at FROM ledger_entries WHERE transfer_id = $1 ORDER BY created_at
`

func (q *Queries) ListLedgerEntriesByTransfer(ctx context.Context, transferID pgtype.UUID) ([]LedgerEntry, error) {
	rows, err := q.db.Query(ctx, listLedgerEntriesByTransfer, transferID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerEntry{}
	for rows.Next() {
		var i LedgerEntry
		if err := rows.Scan(
			&i.ID,
			&i.AccountID,
			&i.Amount,
			&i.TransferID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
