// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger_accounts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerAccount = `-- name: CreateLedgerAccount :one
INSERT INTO ledger_accounts (organization_id, owner_type, owner_id, currency, balance)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, organization_id, owner_type, owner_id, currency, balance, created_at
`

type CreateLedgerAccountParams struct {
	OrganizationID pgtype.UUID
	OwnerType      AccountOwnerKind
	OwnerID        pgtype.UUID
	Currency       string
	Balance        pgtype.Numeric
}

func (q *Queries) CreateLedgerAccount(ctx context.Context, arg CreateLedgerAccountParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, createLedgerAccount,
		arg.OrganizationID,
		arg.OwnerType,
		arg.OwnerID,
		arg.Currency,
		arg.Balance,
	)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Currency,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const deleteLedgerAccount = `-- name: DeleteLedgerAccount :exec
DELETE FROM ledger_accounts WHERE id = $1
`

func (q *Queries) DeleteLedgerAccount(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteLedgerAccount, id)
	return err
}

const getLedgerAccount = `-- name: GetLedgerAccount :one
SELECT id, organization_id, owner_type, owner_id, currency, balance, created_at FROM ledger_accounts WHERE id = $1
`

func (q *Queries) GetLedgerAccount(ctx context.Context, id pgtype.UUID) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, getLedgerAccount, id)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Currency,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerAccounts = `-- name: ListLedgerAccounts :many
SELECT id, organization_id, owner_type, owner_id, currency, balance, created_at FROM ledger_accounts ORDER BY created_at
`

func (q *Queries) ListLedgerAccounts(ctx context.Context) ([]LedgerAccount, error) {
	rows, err := q.db.Query(ctx, listLedgerAccounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerAccount{}
	for rows.Next() {
		var i LedgerAccount
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.OwnerType,
			&i.OwnerID,
			&i.Currency,
			&i.Balance,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLedgerAccountBalance = `-- name: UpdateLedgerAccountBalance :one
UPDATE ledger_accounts SET balance = $2 WHERE id = $1
RETURNING id, organization_id, owner_type, owner_id, currency, balance, created_at
`

type UpdateLedgerAccountBalanceParams struct {
	ID      pgtype.UUID
	Balance pgtype.Numeric
}

func (q *Queries) UpdateLedgerAccountBalance(ctx context.Context, arg UpdateLedgerAccountBalanceParams) (LedgerAccount, error) {
	row := q.db.QueryRow(ctx, updateLedgerAccountBalance, arg.ID, arg.Balance)
	var i LedgerAccount
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.OwnerType,
		&i.OwnerID,
		&i.Currency,
		&i.Balance,
		&i.CreatedAt,
	)
	return i, err
}
