// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: ledger_transfers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createLedgerTransfer = `-- name: CreateLedgerTransfer :one
INSERT INTO ledger_transfers (
    organization_id, transfer_type, invoice_id, method, reference,
    narrative, idempotency_key, reversed_transfer_id, recorded_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, organization_id, transfer_type, invoice_id, method, reference, narrative, idempotency_key, reversed_transfer_id, recorded_by, created_at
`

type CreateLedgerTransferParams struct {
	OrganizationID     pgtype.UUID
	TransferType       TransferKind
	InvoiceID          pgtype.UUID
	Method             PaymentMethod
	Reference          pgtype.Text
	Narrative          pgtype.Text
	IdempotencyKey     string
	ReversedTransferID pgtype.UUID
	RecordedBy         pgtype.UUID
}

func (q *Queries) CreateLedgerTransfer(ctx context.Context, arg CreateLedgerTransferParams) (LedgerTransfer, error) {
	row := q.db.QueryRow(ctx, createLedgerTransfer,
		arg.OrganizationID,
		arg.TransferType,
		arg.InvoiceID,
		arg.Method,
		arg.Reference,
		arg.Narrative,
		arg.IdempotencyKey,
		arg.ReversedTransferID,
		arg.RecordedBy,
	)
	var i LedgerTransfer
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TransferType,
		&i.InvoiceID,
		&i.Method,
		&i.Reference,
		&i.Narrative,
		&i.IdempotencyKey,
		&i.ReversedTransferID,
		&i.RecordedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getLedgerTransfer = `-- name: GetLedgerTransfer :one
SELECT id, organization_id, transfer_type, invoice_id, method, reference, narrative, idempotency_key, reversed_transfer_id, recorded_by, created_at FROM ledger_transfers WHERE id = $1
`

func (q *Queries) GetLedgerTransfer(ctx context.Context, id pgtype.UUID) (LedgerTransfer, error) {
	row := q.db.QueryRow(ctx, getLedgerTransfer, id)
	var i LedgerTransfer
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TransferType,
		&i.InvoiceID,
		&i.Method,
		&i.Reference,
		&i.Narrative,
		&i.IdempotencyKey,
		&i.ReversedTransferID,
		&i.RecordedBy,
		&i.CreatedAt,
	)
	return i, err
}

const getLedgerTransferByIdempotencyKey = `-- name: GetLedgerTransferByIdempotencyKey :one
SELECT id, organization_id, transfer_type, invoice_id, method, reference, narrative, idempotency_key, reversed_transfer_id, recorded_by, created_at FROM ledger_transfers WHERE idempotency_key = $1
`

func (q *Queries) GetLedgerTransferByIdempotencyKey(ctx context.Context, idempotencyKey string) (LedgerTransfer, error) {
	row := q.db.QueryRow(ctx, getLedgerTransferByIdempotencyKey, idempotencyKey)
	var i LedgerTransfer
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.TransferType,
		&i.InvoiceID,
		&i.Method,
		&i.Reference,
		&i.Narrative,
		&i.IdempotencyKey,
		&i.ReversedTransferID,
		&i.RecordedBy,
		&i.CreatedAt,
	)
	return i, err
}

const listLedgerTransfers = `-- name: ListLedgerTransfers :many
SELECT id, organization_id, transfer_type, invoice_id, method, reference, narrative, idempotency_key, reversed_transfer_id, recorded_by, created_at FROM ledger_transfers ORDER BY created_at DESC
`

func (q *Queries) ListLedgerTransfers(ctx context.Context) ([]LedgerTransfer, error) {
	rows, err := q.db.Query(ctx, listLedgerTransfers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []LedgerTransfer{}
	for rows.Next() {
		var i LedgerTransfer
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.TransferType,
			&i.InvoiceID,
			&i.Method,
			&i.Reference,
			&i.Narrative,
			&i.IdempotencyKey,
			&i.ReversedTransferID,
			&i.RecordedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
