// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: meters.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createMeter = `-- name: CreateMeter :one
INSERT INTO meters (unit_id, meter_type, meter_number)
VALUES ($1, $2, $3)
RETURNING id, unit_id, meter_type, meter_number
`

type CreateMeterParams struct {
	UnitID      pgtype.UUID
	MeterType   MeterKind
	MeterNumber pgtype.Text
}

func (q *Queries) CreateMeter(ctx context.Context, arg CreateMeterParams) (Meter, error) {
	row := q.db.QueryRow(ctx, createMeter, arg.UnitID, arg.MeterType, arg.MeterNumber)
	var i Meter
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.MeterType,
		&i.MeterNumber,
	)
	return i, err
}

const deleteMeter = `-- name: DeleteMeter :exec
DELETE FROM meters WHERE id = $1
`

func (q *Queries) DeleteMeter(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteMeter, id)
	return err
}

const getMeter = `-- name: GetMeter :one
SELECT id, unit_id, meter_type, meter_number FROM meters WHERE id = $1
`

func (q *Queries) GetMeter(ctx context.Context, id pgtype.UUID) (Meter, error) {
	row := q.db.QueryRow(ctx, getMeter, id)
	var i Meter
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.MeterType,
		&i.MeterNumber,
	)
	return i, err
}

const listMetersByUnit = `-- name: ListMetersByUnit :many
SELECT id, unit_id, meter_type, meter_number FROM meters WHERE unit_id = $1
`

func (q *Queries) ListMetersByUnit(ctx context.Context, unitID pgtype.UUID) ([]Meter, error) {
	rows, err := q.db.Query(ctx, listMetersByUnit, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Meter{}
	for rows.Next() {
		var i Meter
		if err := rows.Scan(
			&i.ID,
			&i.UnitID,
			&i.MeterType,
			&i.MeterNumber,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateMeter = `-- name: UpdateMeter :one
UPDATE meters SET meter_type = $2, meter_number = $3
WHERE id = $1
RETURNING id, unit_id, meter_type, meter_number
`

type UpdateMeterParams struct {
	ID          pgtype.UUID
	MeterType   MeterKind
	MeterNumber pgtype.Text
}

func (q *Queries) UpdateMeter(ctx context.Context, arg UpdateMeterParams) (Meter, error) {
	row := q.db.QueryRow(ctx, updateMeter, arg.ID, arg.MeterType, arg.MeterNumber)
	var i Meter
	err := row.Scan(
		&i.ID,
		&i.UnitID,
		&i.MeterType,
		&i.MeterNumber,
	)
	return i, err
}
