// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AccountOwnerKind string

const (
	AccountOwnerKindTenant          AccountOwnerKind = "tenant"
	AccountOwnerKindPropertyTill    AccountOwnerKind = "property_till"
	AccountOwnerKindLandlordPayable AccountOwnerKind = "landlord_payable"
	AccountOwnerKindDepositHolding  AccountOwnerKind = "deposit_holding"
)

func (e *AccountOwnerKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AccountOwnerKind(s)
	case string:
		*e = AccountOwnerKind(s)
	default:
		return fmt.Errorf("unsupported scan type for AccountOwnerKind: %T", src)
	}
	return nil
}

type NullAccountOwnerKind struct {
	AccountOwnerKind AccountOwnerKind
	Valid            bool // Valid is true if AccountOwnerKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAccountOwnerKind) Scan(value interface{}) error {
	if value == nil {
		ns.AccountOwnerKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AccountOwnerKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAccountOwnerKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AccountOwnerKind), nil
}

type AddonKind string

const (
	AddonKindVerifiedPropertyScore AddonKind = "verified_property_score"
)

func (e *AddonKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AddonKind(s)
	case string:
		*e = AddonKind(s)
	default:
		return fmt.Errorf("unsupported scan type for AddonKind: %T", src)
	}
	return nil
}

type NullAddonKind struct {
	AddonKind AddonKind
	Valid     bool // Valid is true if AddonKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAddonKind) Scan(value interface{}) error {
	if value == nil {
		ns.AddonKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AddonKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAddonKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AddonKind), nil
}

type AddonStatus string

const (
	AddonStatusInactive  AddonStatus = "inactive"
	AddonStatusActive    AddonStatus = "active"
	AddonStatusPastDue   AddonStatus = "past_due"
	AddonStatusCancelled AddonStatus = "cancelled"
)

func (e *AddonStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AddonStatus(s)
	case string:
		*e = AddonStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AddonStatus: %T", src)
	}
	return nil
}

type NullAddonStatus struct {
	AddonStatus AddonStatus
	Valid       bool // Valid is true if AddonStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAddonStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AddonStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AddonStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAddonStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AddonStatus), nil
}

type InvoiceKind string

const (
	InvoiceKindRent         InvoiceKind = "rent"
	InvoiceKindWaterGarbage InvoiceKind = "water_garbage"
	InvoiceKindDeposit      InvoiceKind = "deposit"
	InvoiceKindLateFee      InvoiceKind = "late_fee"
)

func (e *InvoiceKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceKind(s)
	case string:
		*e = InvoiceKind(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceKind: %T", src)
	}
	return nil
}

type NullInvoiceKind struct {
	InvoiceKind InvoiceKind
	Valid       bool // Valid is true if InvoiceKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceKind) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceKind), nil
}

type InvoiceStatus string

const (
	InvoiceStatusOpen          InvoiceStatus = "open"
	InvoiceStatusPartiallyPaid InvoiceStatus = "partially_paid"
	InvoiceStatusPaid          InvoiceStatus = "paid"
	InvoiceStatusWaived        InvoiceStatus = "waived"
)

func (e *InvoiceStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = InvoiceStatus(s)
	case string:
		*e = InvoiceStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for InvoiceStatus: %T", src)
	}
	return nil
}

type NullInvoiceStatus struct {
	InvoiceStatus InvoiceStatus
	Valid         bool // Valid is true if InvoiceStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullInvoiceStatus) Scan(value interface{}) error {
	if value == nil {
		ns.InvoiceStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.InvoiceStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullInvoiceStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.InvoiceStatus), nil
}

type LeaseStatus string

const (
	LeaseStatusActive       LeaseStatus = "active"
	LeaseStatusTerminated   LeaseStatus = "terminated"
	LeaseStatusNoticePeriod LeaseStatus = "notice_period"
)

func (e *LeaseStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeaseStatus(s)
	case string:
		*e = LeaseStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LeaseStatus: %T", src)
	}
	return nil
}

type NullLeaseStatus struct {
	LeaseStatus LeaseStatus
	Valid       bool // Valid is true if LeaseStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLeaseStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LeaseStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LeaseStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLeaseStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LeaseStatus), nil
}

type MeterKind string

const (
	MeterKindWater MeterKind = "water"
)

func (e *MeterKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MeterKind(s)
	case string:
		*e = MeterKind(s)
	default:
		return fmt.Errorf("unsupported scan type for MeterKind: %T", src)
	}
	return nil
}

type NullMeterKind struct {
	MeterKind MeterKind
	Valid     bool // Valid is true if MeterKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMeterKind) Scan(value interface{}) error {
	if value == nil {
		ns.MeterKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MeterKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMeterKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MeterKind), nil
}

type OrgBillingStatus string

const (
	OrgBillingStatusActive    OrgBillingStatus = "active"
	OrgBillingStatusPastDue   OrgBillingStatus = "past_due"
	OrgBillingStatusSuspended OrgBillingStatus = "suspended"
)

func (e *OrgBillingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OrgBillingStatus(s)
	case string:
		*e = OrgBillingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OrgBillingStatus: %T", src)
	}
	return nil
}

type NullOrgBillingStatus struct {
	OrgBillingStatus OrgBillingStatus
	Valid            bool // Valid is true if OrgBillingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOrgBillingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OrgBillingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OrgBillingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOrgBillingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OrgBillingStatus), nil
}

type PaymentMethod string

const (
	PaymentMethodCash          PaymentMethod = "cash"
	PaymentMethodMpesaManual   PaymentMethod = "mpesa_manual"
	PaymentMethodBank          PaymentMethod = "bank"
	PaymentMethodCheque        PaymentMethod = "cheque"
	PaymentMethodIntasendMpesa PaymentMethod = "intasend_mpesa"
	PaymentMethodIntasendCard  PaymentMethod = "intasend_card"
)

func (e *PaymentMethod) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PaymentMethod(s)
	case string:
		*e = PaymentMethod(s)
	default:
		return fmt.Errorf("unsupported scan type for PaymentMethod: %T", src)
	}
	return nil
}

type NullPaymentMethod struct {
	PaymentMethod PaymentMethod
	Valid         bool // Valid is true if PaymentMethod is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPaymentMethod) Scan(value interface{}) error {
	if value == nil {
		ns.PaymentMethod, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PaymentMethod.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPaymentMethod) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PaymentMethod), nil
}

type PayoutDocKind string

const (
	PayoutDocKindCertificateOfIncorporation PayoutDocKind = "certificate_of_incorporation"
	PayoutDocKindNationalID                 PayoutDocKind = "national_id"
)

func (e *PayoutDocKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PayoutDocKind(s)
	case string:
		*e = PayoutDocKind(s)
	default:
		return fmt.Errorf("unsupported scan type for PayoutDocKind: %T", src)
	}
	return nil
}

type NullPayoutDocKind struct {
	PayoutDocKind PayoutDocKind
	Valid         bool // Valid is true if PayoutDocKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPayoutDocKind) Scan(value interface{}) error {
	if value == nil {
		ns.PayoutDocKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PayoutDocKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPayoutDocKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PayoutDocKind), nil
}

type PayoutKycStatus string

const (
	PayoutKycStatusPending  PayoutKycStatus = "pending"
	PayoutKycStatusVerified PayoutKycStatus = "verified"
	PayoutKycStatusRejected PayoutKycStatus = "rejected"
)

func (e *PayoutKycStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PayoutKycStatus(s)
	case string:
		*e = PayoutKycStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for PayoutKycStatus: %T", src)
	}
	return nil
}

type NullPayoutKycStatus struct {
	PayoutKycStatus PayoutKycStatus
	Valid           bool // Valid is true if PayoutKycStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPayoutKycStatus) Scan(value interface{}) error {
	if value == nil {
		ns.PayoutKycStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PayoutKycStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPayoutKycStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PayoutKycStatus), nil
}

type SubscriptionTier string

const (
	SubscriptionTierStarter      SubscriptionTier = "starter"
	SubscriptionTierGrowth       SubscriptionTier = "growth"
	SubscriptionTierProfessional SubscriptionTier = "professional"
	SubscriptionTierEnterprise   SubscriptionTier = "enterprise"
)

func (e *SubscriptionTier) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SubscriptionTier(s)
	case string:
		*e = SubscriptionTier(s)
	default:
		return fmt.Errorf("unsupported scan type for SubscriptionTier: %T", src)
	}
	return nil
}

type NullSubscriptionTier struct {
	SubscriptionTier SubscriptionTier
	Valid            bool // Valid is true if SubscriptionTier is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSubscriptionTier) Scan(value interface{}) error {
	if value == nil {
		ns.SubscriptionTier, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SubscriptionTier.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSubscriptionTier) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SubscriptionTier), nil
}

type TransferKind string

const (
	TransferKindRentPayment          TransferKind = "rent_payment"
	TransferKindWaterPayment         TransferKind = "water_payment"
	TransferKindDepositPayment       TransferKind = "deposit_payment"
	TransferKindDepositRefund        TransferKind = "deposit_refund"
	TransferKindRemittanceToLandlord TransferKind = "remittance_to_landlord"
	TransferKindLateFeeCharge        TransferKind = "late_fee_charge"
	TransferKindReversal             TransferKind = "reversal"
)

func (e *TransferKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = TransferKind(s)
	case string:
		*e = TransferKind(s)
	default:
		return fmt.Errorf("unsupported scan type for TransferKind: %T", src)
	}
	return nil
}

type NullTransferKind struct {
	TransferKind TransferKind
	Valid        bool // Valid is true if TransferKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullTransferKind) Scan(value interface{}) error {
	if value == nil {
		ns.TransferKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.TransferKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullTransferKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.TransferKind), nil
}

type UnitStatus string

const (
	UnitStatusVacant      UnitStatus = "vacant"
	UnitStatusOccupied    UnitStatus = "occupied"
	UnitStatusNoticeGiven UnitStatus = "notice_given"
)

func (e *UnitStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UnitStatus(s)
	case string:
		*e = UnitStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UnitStatus: %T", src)
	}
	return nil
}

type NullUnitStatus struct {
	UnitStatus UnitStatus
	Valid      bool // Valid is true if UnitStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUnitStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UnitStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UnitStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUnitStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UnitStatus), nil
}

type UserRole string

const (
	UserRoleLandlord UserRole = "landlord"
	UserRoleManager  UserRole = "manager"
	UserRoleAgent    UserRole = "agent"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type UserStatus string

const (
	UserStatusInvited   UserStatus = "invited"
	UserStatusActive    UserStatus = "active"
	UserStatusSuspended UserStatus = "suspended"
)

func (e *UserStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserStatus(s)
	case string:
		*e = UserStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for UserStatus: %T", src)
	}
	return nil
}

type NullUserStatus struct {
	UserStatus UserStatus
	Valid      bool // Valid is true if UserStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserStatus) Scan(value interface{}) error {
	if value == nil {
		ns.UserStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserStatus), nil
}

type AgentPropertyGrant struct {
	ID                      pgtype.UUID
	AgentID                 pgtype.UUID
	PropertyID              pgtype.UUID
	CanRecordPayments       bool
	CanEditLeases           bool
	CanEditUnitPricing      bool
	CanVoidPayments         bool
	CanViewFinancialReports bool
	CanManageMeterReadings  bool
	GrantedBy               pgtype.UUID
	GrantedAt               pgtype.Timestamptz
	RevokedAt               pgtype.Timestamptz
}

type AuditLog struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	PropertyID     pgtype.UUID
	ActorID        pgtype.UUID
	Action         string
	EntityType     string
	EntityID       pgtype.UUID
	Metadata       []byte
	CreatedAt      pgtype.Timestamptz
}

type ElectricityTopup struct {
	ID             pgtype.UUID
	UnitID         pgtype.UUID
	ReportedBy     pgtype.UUID
	Amount         pgtype.Numeric
	TokenReference pgtype.Text
	ReportedAt     pgtype.Timestamptz
}

type Invoice struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	LeaseID        pgtype.UUID
	PeriodMonth    pgtype.Date
	InvoiceType    InvoiceKind
	AmountDue      pgtype.Numeric
	AmountPaid     pgtype.Numeric
	Balance        pgtype.Numeric
	Status         InvoiceStatus
	MeterReadingID pgtype.UUID
	CreatedAt      pgtype.Timestamptz
}

type Lease struct {
	ID               pgtype.UUID
	UnitID           pgtype.UUID
	TenantID         pgtype.UUID
	MonthlyRent      pgtype.Numeric
	DepositPaid      pgtype.Numeric
	StartDate        pgtype.Date
	EndDate          pgtype.Date
	RentDueDay       int16
	LateFeePctPerDay pgtype.Numeric
	Status           LeaseStatus
	TerminatedReason pgtype.Text
	TerminatedAt     pgtype.Timestamptz
	CreatedBy        pgtype.UUID
	CreatedAt        pgtype.Timestamptz
}

type LedgerAccount struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	OwnerType      AccountOwnerKind
	OwnerID        pgtype.UUID
	Currency       string
	Balance        pgtype.Numeric
	CreatedAt      pgtype.Timestamptz
}

type LedgerEntry struct {
	ID         pgtype.UUID
	AccountID  pgtype.UUID
	Amount     pgtype.Numeric
	TransferID pgtype.UUID
	CreatedAt  pgtype.Timestamptz
}

type LedgerTransfer struct {
	ID                 pgtype.UUID
	OrganizationID     pgtype.UUID
	TransferType       TransferKind
	InvoiceID          pgtype.UUID
	Method             PaymentMethod
	Reference          pgtype.Text
	Narrative          pgtype.Text
	IdempotencyKey     string
	ReversedTransferID pgtype.UUID
	RecordedBy         pgtype.UUID
	CreatedAt          pgtype.Timestamptz
}

type ManagerPayoutAccount struct {
	ID                   pgtype.UUID
	OrganizationID       pgtype.UUID
	ManagerID            pgtype.UUID
	BankName             string
	BankBranchCode       pgtype.Text
	AccountName          string
	AccountNumber        string
	KraPin               string
	BusinessDocType      PayoutDocKind
	BusinessDocReference string
	GatewayProvider      string
	GatewaySubaccountID  pgtype.Text
	KycStatus            PayoutKycStatus
	KycSubmittedAt       pgtype.Timestamptz
	KycVerifiedAt        pgtype.Timestamptz
	KycRejectionReason   pgtype.Text
	CreatedAt            pgtype.Timestamptz
	UpdatedAt            pgtype.Timestamptz
}

type Meter struct {
	ID          pgtype.UUID
	UnitID      pgtype.UUID
	MeterType   MeterKind
	MeterNumber pgtype.Text
}

type MeterReading struct {
	ID              pgtype.UUID
	MeterID         pgtype.UUID
	ReadingMonth    pgtype.Date
	PreviousReading pgtype.Numeric
	CurrentReading  pgtype.Numeric
	UnitsConsumed   pgtype.Numeric
	RatePerM3       pgtype.Numeric
	AmountDue       pgtype.Numeric
	RecordedBy      pgtype.UUID
	RecordedAt      pgtype.Timestamptz
}

type Organization struct {
	ID               pgtype.UUID
	Name             string
	BrandName        string
	SubscriptionTier SubscriptionTier
	BillingStatus    OrgBillingStatus
	OwnerUserID      pgtype.UUID
	CreatedAt        pgtype.Timestamptz
	UpdatedAt        pgtype.Timestamptz
	Slug             string
	LogoUrl          pgtype.Text
	AccentKey        string
	SmsSenderID      pgtype.Text
	EmailFromName    pgtype.Text
}

type OrganizationAddon struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	AddonKey       AddonKind
	Status         AddonStatus
	MonthlyFeeKes  pgtype.Numeric
	ActivatedAt    pgtype.Timestamptz
	CancelledAt    pgtype.Timestamptz
}

type PaymentGatewayTransaction struct {
	ID                  pgtype.UUID
	OrganizationID      pgtype.UUID
	GatewayProvider     string
	GatewayReference    string
	GatewaySubaccountID string
	UnitID              pgtype.UUID
	InvoiceID           pgtype.UUID
	Amount              pgtype.Numeric
	Currency            string
	Channel             string
	Status              string
	RawPayload          []byte
	LedgerTransferID    pgtype.UUID
	ReceivedAt          pgtype.Timestamptz
}

type Property struct {
	ID               pgtype.UUID
	OrganizationID   pgtype.UUID
	ManagerID        pgtype.UUID
	Name             string
	Location         string
	BrandNote        pgtype.Text
	WaterRatePerM3   pgtype.Numeric
	GarbageFeeFlat   pgtype.Numeric
	LateFeePctPerDay pgtype.Numeric
	RentDueDay       int16
	CreatedAt        pgtype.Timestamptz
}

type PropertyOwnership struct {
	PropertyID   pgtype.UUID
	LandlordID   pgtype.UUID
	OwnershipPct pgtype.Numeric
}

type PropertyScore struct {
	ID              pgtype.UUID
	OrganizationID  pgtype.UUID
	PropertyID      pgtype.UUID
	ComputedAt      pgtype.Timestamptz
	AsOfDate        pgtype.Date
	ModelVersion    string
	Noi             pgtype.Numeric
	Dscr            pgtype.Numeric
	ScoreValue      pgtype.Numeric
	ScoreBand       string
	FeatureSnapshot []byte
	RequestedBy     pgtype.UUID
}

type Session struct {
	ID               pgtype.UUID
	UserID           pgtype.UUID
	OrganizationID   pgtype.UUID
	RefreshTokenHash pgtype.Text
	DeviceLabel      pgtype.Text
	ExpiresAt        pgtype.Timestamptz
	RevokedAt        pgtype.Timestamptz
}

type SubscriptionCharge struct {
	ID                 pgtype.UUID
	OrganizationID     pgtype.UUID
	ManagerID          pgtype.UUID
	Tier               SubscriptionTier
	AmountKes          pgtype.Numeric
	GatewayProvider    string
	GatewayReference   string
	Status             string
	BillingPeriodStart pgtype.Date
	BillingPeriodEnd   pgtype.Date
	RawPayload         []byte
	CreatedAt          pgtype.Timestamptz
	UpdatedAt          pgtype.Timestamptz
}

type Tenant struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	FullName       string
	Phone          string
	IDNumber       pgtype.Text
	CreatedAt      pgtype.Timestamptz
}

type TenantImportBatch struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	PropertyID     pgtype.UUID
	UploadedBy     pgtype.UUID
	Filename       string
	RowCount       int32
	CreatedCount   int32
	SkippedCount   int32
	RowResults     []byte
	CreatedAt      pgtype.Timestamptz
}

type Token struct {
	Hash           []byte
	UserID         pgtype.UUID
	OrganizationID pgtype.UUID
	Expiry         pgtype.Timestamptz
	Scope          string
}

type Unit struct {
	ID            pgtype.UUID
	PropertyID    pgtype.UUID
	UnitLabel     string
	UnitType      pgtype.Text
	BaseRent      pgtype.Numeric
	DepositAmount pgtype.Numeric
	Status        UnitStatus
}

type User struct {
	ID             pgtype.UUID
	OrganizationID pgtype.UUID
	FullName       string
	Phone          string
	Email          string
	PasswordHash   pgtype.Text
	Role           UserRole
	IsSuperManager bool
	Activated      bool
	Status         UserStatus
	InvitedBy      pgtype.UUID
	CreatedAt      pgtype.Timestamptz
	UpdatedAt      pgtype.Timestamptz
}

type VUnitStatement struct {
	UnitID      pgtype.UUID
	PeriodMonth pgtype.Date
	RentDue     interface{}
	RentPaid    interface{}
	WaterDue    interface{}
	WaterPaid   interface{}
}
