// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: properties.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProperty = `-- name: CreateProperty :one
INSERT INTO properties (
    organization_id, manager_id, name, location, brand_note,
    water_rate_per_m3, garbage_fee_flat, late_fee_pct_per_day, rent_due_day
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id, organization_id, manager_id, name, location, brand_note, water_rate_per_m3, garbage_fee_flat, late_fee_pct_per_day, rent_due_day, created_at
`

type CreatePropertyParams struct {
	OrganizationID   pgtype.UUID
	ManagerID        pgtype.UUID
	Name             string
	Location         string
	BrandNote        pgtype.Text
	WaterRatePerM3   pgtype.Numeric
	GarbageFeeFlat   pgtype.Numeric
	LateFeePctPerDay pgtype.Numeric
	RentDueDay       int16
}

func (q *Queries) CreateProperty(ctx context.Context, arg CreatePropertyParams) (Property, error) {
	row := q.db.QueryRow(ctx, createProperty,
		arg.OrganizationID,
		arg.ManagerID,
		arg.Name,
		arg.Location,
		arg.BrandNote,
		arg.WaterRatePerM3,
		arg.GarbageFeeFlat,
		arg.LateFeePctPerDay,
		arg.RentDueDay,
	)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ManagerID,
		&i.Name,
		&i.Location,
		&i.BrandNote,
		&i.WaterRatePerM3,
		&i.GarbageFeeFlat,
		&i.LateFeePctPerDay,
		&i.RentDueDay,
		&i.CreatedAt,
	)
	return i, err
}

const deleteProperty = `-- name: DeleteProperty :exec
DELETE FROM properties WHERE id = $1
`

func (q *Queries) DeleteProperty(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteProperty, id)
	return err
}

const getProperty = `-- name: GetProperty :one
SELECT id, organization_id, manager_id, name, location, brand_note, water_rate_per_m3, garbage_fee_flat, late_fee_pct_per_day, rent_due_day, created_at FROM properties WHERE id = $1
`

func (q *Queries) GetProperty(ctx context.Context, id pgtype.UUID) (Property, error) {
	row := q.db.QueryRow(ctx, getProperty, id)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ManagerID,
		&i.Name,
		&i.Location,
		&i.BrandNote,
		&i.WaterRatePerM3,
		&i.GarbageFeeFlat,
		&i.LateFeePctPerDay,
		&i.RentDueDay,
		&i.CreatedAt,
	)
	return i, err
}

const listProperties = `-- name: ListProperties :many
SELECT id, organization_id, manager_id, name, location, brand_note, water_rate_per_m3, garbage_fee_flat, late_fee_pct_per_day, rent_due_day, created_at FROM properties ORDER BY name
`

func (q *Queries) ListProperties(ctx context.Context) ([]Property, error) {
	rows, err := q.db.Query(ctx, listProperties)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Property{}
	for rows.Next() {
		var i Property
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.ManagerID,
			&i.Name,
			&i.Location,
			&i.BrandNote,
			&i.WaterRatePerM3,
			&i.GarbageFeeFlat,
			&i.LateFeePctPerDay,
			&i.RentDueDay,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateProperty = `-- name: UpdateProperty :one
UPDATE properties SET
    name = $2,
    location = $3,
    brand_note = $4,
    water_rate_per_m3 = $5,
    garbage_fee_flat = $6,
    late_fee_pct_per_day = $7,
    rent_due_day = $8
WHERE id = $1
RETURNING id, organization_id, manager_id, name, location, brand_note, water_rate_per_m3, garbage_fee_flat, late_fee_pct_per_day, rent_due_day, created_at
`

type UpdatePropertyParams struct {
	ID               pgtype.UUID
	Name             string
	Location         string
	BrandNote        pgtype.Text
	WaterRatePerM3   pgtype.Numeric
	GarbageFeeFlat   pgtype.Numeric
	LateFeePctPerDay pgtype.Numeric
	RentDueDay       int16
}

func (q *Queries) UpdateProperty(ctx context.Context, arg UpdatePropertyParams) (Property, error) {
	row := q.db.QueryRow(ctx, updateProperty,
		arg.ID,
		arg.Name,
		arg.Location,
		arg.BrandNote,
		arg.WaterRatePerM3,
		arg.GarbageFeeFlat,
		arg.LateFeePctPerDay,
		arg.RentDueDay,
	)
	var i Property
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.ManagerID,
		&i.Name,
		&i.Location,
		&i.BrandNote,
		&i.WaterRatePerM3,
		&i.GarbageFeeFlat,
		&i.LateFeePctPerDay,
		&i.RentDueDay,
		&i.CreatedAt,
	)
	return i, err
}
