// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: tokens.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createToken = `-- name: CreateToken :one
INSERT INTO tokens (hash, user_id, organization_id, expiry, scope)
VALUES ($1, $2, $3, $4, $5)
RETURNING hash, user_id, organization_id, expiry, scope
`

type CreateTokenParams struct {
	Hash           []byte
	UserID         pgtype.UUID
	OrganizationID pgtype.UUID
	Expiry         pgtype.Timestamptz
	Scope          string
}

func (q *Queries) CreateToken(ctx context.Context, arg CreateTokenParams) (Token, error) {
	row := q.db.QueryRow(ctx, createToken,
		arg.Hash,
		arg.UserID,
		arg.OrganizationID,
		arg.Expiry,
		arg.Scope,
	)
	var i Token
	err := row.Scan(
		&i.Hash,
		&i.UserID,
		&i.OrganizationID,
		&i.Expiry,
		&i.Scope,
	)
	return i, err
}

const deleteToken = `-- name: DeleteToken :exec
DELETE FROM tokens WHERE hash = $1
`

func (q *Queries) DeleteToken(ctx context.Context, hash []byte) error {
	_, err := q.db.Exec(ctx, deleteToken, hash)
	return err
}

const getToken = `-- name: GetToken :one
SELECT hash, user_id, organization_id, expiry, scope FROM tokens WHERE hash = $1
`

func (q *Queries) GetToken(ctx context.Context, hash []byte) (Token, error) {
	row := q.db.QueryRow(ctx, getToken, hash)
	var i Token
	err := row.Scan(
		&i.Hash,
		&i.UserID,
		&i.OrganizationID,
		&i.Expiry,
		&i.Scope,
	)
	return i, err
}

const listTokensByUser = `-- name: ListTokensByUser :many
SELECT hash, user_id, organization_id, expiry, scope FROM tokens WHERE user_id = $1 ORDER BY expiry
`

func (q *Queries) ListTokensByUser(ctx context.Context, userID pgtype.UUID) ([]Token, error) {
	rows, err := q.db.Query(ctx, listTokensByUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Token{}
	for rows.Next() {
		var i Token
		if err := rows.Scan(
			&i.Hash,
			&i.UserID,
			&i.OrganizationID,
			&i.Expiry,
			&i.Scope,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
