// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: units.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUnit = `-- name: CreateUnit :one
INSERT INTO units (property_id, unit_label, unit_type, base_rent, deposit_amount, status)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, property_id, unit_label, unit_type, base_rent, deposit_amount, status
`

type CreateUnitParams struct {
	PropertyID    pgtype.UUID
	UnitLabel     string
	UnitType      pgtype.Text
	BaseRent      pgtype.Numeric
	DepositAmount pgtype.Numeric
	Status        UnitStatus
}

func (q *Queries) CreateUnit(ctx context.Context, arg CreateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, createUnit,
		arg.PropertyID,
		arg.UnitLabel,
		arg.UnitType,
		arg.BaseRent,
		arg.DepositAmount,
		arg.Status,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.UnitLabel,
		&i.UnitType,
		&i.BaseRent,
		&i.DepositAmount,
		&i.Status,
	)
	return i, err
}

const deleteUnit = `-- name: DeleteUnit :exec
DELETE FROM units WHERE id = $1
`

func (q *Queries) DeleteUnit(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUnit, id)
	return err
}

const getUnit = `-- name: GetUnit :one
SELECT id, property_id, unit_label, unit_type, base_rent, deposit_amount, status FROM units WHERE id = $1
`

func (q *Queries) GetUnit(ctx context.Context, id pgtype.UUID) (Unit, error) {
	row := q.db.QueryRow(ctx, getUnit, id)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.UnitLabel,
		&i.UnitType,
		&i.BaseRent,
		&i.DepositAmount,
		&i.Status,
	)
	return i, err
}

const listUnitsByProperty = `-- name: ListUnitsByProperty :many
SELECT id, property_id, unit_label, unit_type, base_rent, deposit_amount, status FROM units WHERE property_id = $1 ORDER BY unit_label
`

func (q *Queries) ListUnitsByProperty(ctx context.Context, propertyID pgtype.UUID) ([]Unit, error) {
	rows, err := q.db.Query(ctx, listUnitsByProperty, propertyID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Unit{}
	for rows.Next() {
		var i Unit
		if err := rows.Scan(
			&i.ID,
			&i.PropertyID,
			&i.UnitLabel,
			&i.UnitType,
			&i.BaseRent,
			&i.DepositAmount,
			&i.Status,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUnit = `-- name: UpdateUnit :one
UPDATE units SET
    unit_label = $2,
    unit_type = $3,
    base_rent = $4,
    deposit_amount = $5,
    status = $6
WHERE id = $1
RETURNING id, property_id, unit_label, unit_type, base_rent, deposit_amount, status
`

type UpdateUnitParams struct {
	ID            pgtype.UUID
	UnitLabel     string
	UnitType      pgtype.Text
	BaseRent      pgtype.Numeric
	DepositAmount pgtype.Numeric
	Status        UnitStatus
}

func (q *Queries) UpdateUnit(ctx context.Context, arg UpdateUnitParams) (Unit, error) {
	row := q.db.QueryRow(ctx, updateUnit,
		arg.ID,
		arg.UnitLabel,
		arg.UnitType,
		arg.BaseRent,
		arg.DepositAmount,
		arg.Status,
	)
	var i Unit
	err := row.Scan(
		&i.ID,
		&i.PropertyID,
		&i.UnitLabel,
		&i.UnitType,
		&i.BaseRent,
		&i.DepositAmount,
		&i.Status,
	)
	return i, err
}
