// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createUser = `-- name: CreateUser :one
INSERT INTO users (
    organization_id, full_name, phone, email, password_hash,
    role, is_super_manager, activated, status, invited_by
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
RETURNING id, organization_id, full_name, phone, email, password_hash, role, is_super_manager, activated, status, invited_by, created_at, updated_at
`

type CreateUserParams struct {
	OrganizationID pgtype.UUID
	FullName       string
	Phone          string
	Email          string
	PasswordHash   pgtype.Text
	Role           UserRole
	IsSuperManager bool
	Activated      bool
	Status         UserStatus
	InvitedBy      pgtype.UUID
}

func (q *Queries) CreateUser(ctx context.Context, arg CreateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, createUser,
		arg.OrganizationID,
		arg.FullName,
		arg.Phone,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.IsSuperManager,
		arg.Activated,
		arg.Status,
		arg.InvitedBy,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsSuperManager,
		&i.Activated,
		&i.Status,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteUser = `-- name: DeleteUser :exec
DELETE FROM users WHERE id = $1
`

func (q *Queries) DeleteUser(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteUser, id)
	return err
}

const getUser = `-- name: GetUser :one
SELECT id, organization_id, full_name, phone, email, password_hash, role, is_super_manager, activated, status, invited_by, created_at, updated_at FROM users WHERE id = $1
`

func (q *Queries) GetUser(ctx context.Context, id pgtype.UUID) (User, error) {
	row := q.db.QueryRow(ctx, getUser, id)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsSuperManager,
		&i.Activated,
		&i.Status,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserByEmail = `-- name: GetUserByEmail :one
SELECT id, organization_id, full_name, phone, email, password_hash, role, is_super_manager, activated, status, invited_by, created_at, updated_at FROM users WHERE email = $1
`

func (q *Queries) GetUserByEmail(ctx context.Context, email string) (User, error) {
	row := q.db.QueryRow(ctx, getUserByEmail, email)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsSuperManager,
		&i.Activated,
		&i.Status,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listUsersByOrganization = `-- name: ListUsersByOrganization :many
SELECT id, organization_id, full_name, phone, email, password_hash, role, is_super_manager, activated, status, invited_by, created_at, updated_at FROM users WHERE organization_id = $1 ORDER BY full_name
`

func (q *Queries) ListUsersByOrganization(ctx context.Context, organizationID pgtype.UUID) ([]User, error) {
	rows, err := q.db.Query(ctx, listUsersByOrganization, organizationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []User{}
	for rows.Next() {
		var i User
		if err := rows.Scan(
			&i.ID,
			&i.OrganizationID,
			&i.FullName,
			&i.Phone,
			&i.Email,
			&i.PasswordHash,
			&i.Role,
			&i.IsSuperManager,
			&i.Activated,
			&i.Status,
			&i.InvitedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateUser = `-- name: UpdateUser :one
UPDATE users SET
    full_name = $2,
    phone = $3,
    email = $4,
    password_hash = $5,
    role = $6,
    is_super_manager = $7,
    activated = $8,
    status = $9,
    updated_at = now()
WHERE id = $1
RETURNING id, organization_id, full_name, phone, email, password_hash, role, is_super_manager, activated, status, invited_by, created_at, updated_at
`

type UpdateUserParams struct {
	ID             pgtype.UUID
	FullName       string
	Phone          string
	Email          string
	PasswordHash   pgtype.Text
	Role           UserRole
	IsSuperManager bool
	Activated      bool
	Status         UserStatus
}

func (q *Queries) UpdateUser(ctx context.Context, arg UpdateUserParams) (User, error) {
	row := q.db.QueryRow(ctx, updateUser,
		arg.ID,
		arg.FullName,
		arg.Phone,
		arg.Email,
		arg.PasswordHash,
		arg.Role,
		arg.IsSuperManager,
		arg.Activated,
		arg.Status,
	)
	var i User
	err := row.Scan(
		&i.ID,
		&i.OrganizationID,
		&i.FullName,
		&i.Phone,
		&i.Email,
		&i.PasswordHash,
		&i.Role,
		&i.IsSuperManager,
		&i.Activated,
		&i.Status,
		&i.InvitedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
