// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: views.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getUnitStatement = `-- name: GetUnitStatement :many
SELECT unit_id, period_month, rent_due, rent_paid, water_due, water_paid
FROM v_unit_statement
WHERE unit_id = $1
ORDER BY period_month
`

func (q *Queries) GetUnitStatement(ctx context.Context, unitID pgtype.UUID) ([]VUnitStatement, error) {
	rows, err := q.db.Query(ctx, getUnitStatement, unitID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []VUnitStatement{}
	for rows.Next() {
		var i VUnitStatement
		if err := rows.Scan(
			&i.UnitID,
			&i.PeriodMonth,
			&i.RentDue,
			&i.RentPaid,
			&i.WaterDue,
			&i.WaterPaid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnitStatement = `-- name: ListUnitStatement :many
SELECT unit_id,
       period_month,
       rent_due::numeric AS rent_due,
       rent_paid::numeric AS rent_paid,
       water_due::numeric AS water_due,
       water_paid::numeric AS water_paid,
       COUNT(*) OVER()::bigint AS total_count
FROM v_unit_statement
WHERE unit_id = $1
  AND (
      $2::text <> 'landlord'
      OR EXISTS (
          SELECT 1
          FROM units u
          JOIN property_ownership po ON po.property_id = u.property_id
          WHERE u.id = v_unit_statement.unit_id
            AND po.landlord_id = $3::uuid
      )
  )
ORDER BY period_month DESC
LIMIT $4 OFFSET $5
`

type ListUnitStatementParams struct {
	UnitID  pgtype.UUID
	Column2 string
	Column3 pgtype.UUID
	Limit   int32
	Offset  int32
}

type ListUnitStatementRow struct {
	UnitID      pgtype.UUID
	PeriodMonth pgtype.Date
	RentDue     pgtype.Numeric
	RentPaid    pgtype.Numeric
	WaterDue    pgtype.Numeric
	WaterPaid   pgtype.Numeric
	TotalCount  int64
}

func (q *Queries) ListUnitStatement(ctx context.Context, arg ListUnitStatementParams) ([]ListUnitStatementRow, error) {
	rows, err := q.db.Query(ctx, listUnitStatement,
		arg.UnitID,
		arg.Column2,
		arg.Column3,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ListUnitStatementRow{}
	for rows.Next() {
		var i ListUnitStatementRow
		if err := rows.Scan(
			&i.UnitID,
			&i.PeriodMonth,
			&i.RentDue,
			&i.RentPaid,
			&i.WaterDue,
			&i.WaterPaid,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
